-- MySQL Script generated by MySQL Workbench
-- Tue Sep 24 23:06:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`banca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`banca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `saldo_inicial` DOUBLE NULL DEFAULT 0,
  `data_inicial` DATE NULL,
  `moeda` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimentacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saldo_anterior` DOUBLE NULL DEFAULT 0,
  `novo_saldo` DOUBLE NULL DEFAULT 0,
  `data` DATETIME NULL DEFAULT now(),
  `percentual` DOUBLE NULL DEFAULT 0,
  `id_banca` INT NOT NULL,
  `banca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimentacao_banca1_idx` (`banca_id` ASC) VISIBLE,
  CONSTRAINT `fk_movimentacao_banca1`
    FOREIGN KEY (`banca_id`)
    REFERENCES `mydb`.`banca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objetivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `data_inicial` DATE NULL,
  `data_final` DATE NULL,
  `id_banca` INT NOT NULL,
  `banca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_objetivo_banca1_idx` (`banca_id` ASC) VISIBLE,
  CONSTRAINT `fk_objetivo_banca1`
    FOREIGN KEY (`banca_id`)
    REFERENCES `mydb`.`banca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
